### ISSUE TITLE
Tests is successful but installation fails on Strawberry Perl 5.20.3 etc.

### ISSUE THREAD

**Issue by twata1** [Perl5-FFI/Alt-FFI-libffi#4]
Hi,

I was at a loss which way I should report to

[Alt::FFI::libffi issues](https://github.com/Perl5-FFI/Alt-FFI-libffi/issues)
or
[ExtUtils::Install issues](https://github.com/Perl-Toolchain-Gang/ExtUtils-Install/issues) .

I encounterd the issue for the first time during Alt::FFI::libffi 0.05 installation, so I report this here.

Running Strawberry Perl(32bit):
5.20.3
5.22.2
5.24.0
5.26.0
5.26.1
5.28.0

on Windows 7(32bit), I noticed the messages like this:
(In fact, I translated "The filename, directory name, or volume label syntax is incorrect." into English.)

[Example for Strawberry Perl 5.20.3]
```C:\home\grape>cpan PLICEASE/Alt-FFI-libffi-0.05.tar.gz```

(snip)

```
Result: PASS
(c:\Strawberry\c\bin\dmake.exe test exited with 0)
CPAN::Reporter: Test result is 'pass', All tests successful.
CPAN::Reporter: preparing a CPAN Testers report for Alt-FFI-libffi-0.05
CPAN::Reporter: sending test report with 'pass' via Metabase
  PLICEASE/Alt-FFI-libffi-0.05.tar.gz
  c:\Strawberry\c\bin\dmake.exe test -- OK
Running make install for PLICEASE/Alt-FFI-libffi-0.05.tar.gz
"C:\Strawberry\perl\bin\perl.exe" -MFFI::Build::MM=cmd -e fbx_build
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
ERROR: Can't create 'no-install-altC:\home\grape\perl5\lib\perl5'
mkdir no-install-altC:\: Invalid argument; The filename, directory name, or volume label syntax is incorrect. at C:\home\grape\perl5\lib\perl5/ExtUtils/Install.pm line 489.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 at -e line 1.
dmake.exe:  Error code 150, while making 'pure_site_install'
  PLICEASE/Alt-FFI-libffi-0.05.tar.gz
  c:\Strawberry\c\bin\dmake.exe install UNINST=1 -- NOT OK
Stopping: 'install' failed for 'P/PL/PLICEASE/Alt-FFI-libffi-0.05.tar.gz'.

C:\home\grape>perl -MExtUtils::Install -e "print $ExtUtils::Install::VERSION"
2.14
C:\home\grape>
```

Thank you,

**Comment by plicease** [comment]
This is expected behavior, `Alt::FFI::libffi` is an "alternative" implementation for `FFI` (see https://metacpan.org/pod/Alt) for details.   You can force this version to be installed instead of the "real" FFI distribution by setting the `PERL_ALT_INSTALL` environment variable, like so:

```
env PERL_ALT_INSTALL=OVERWRITE cpanm Alt::FFI::libffi
```

I recommend though that you use `FFI::Platypus` over either this distro or the "real" FFI.  It is much more powerful (in the case of `Alt::FFI::libffi` and `FFI`) and is based on libffi which is actively under development (unlike `FFI` which is based on the unmaintained ffcall).

The diagnostic is not particularly helpful on windows... it may make sense to improve on this; `Dist::Zilla::Plugin::Alt` is the dzil plugin responsible for the behavior.

**Comment by plicease** [comment]
Of course on windows the incantation would be more like:

```
C:> set PERL_ALT_INSTALL=OVERWRITE
C:> cpanm Alt::FFI::libffi
```

**Comment by twata1** [comment]
Thank you for letting me know me https://metacpan.org/pod/Alt .
I read https://metacpan.org/pod/Alt .
I understand.

Thank you,
